/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wahidiyanpost;

import javax.swing.JLabel;
import model.Berita;

/**
 *
 * @author Lenovo - GK
 */
public class DetailBerita extends javax.swing.JFrame {

    /**
     * Creates new form DetailBerita
     */
    public DetailBerita() {
        initComponents();
        
        for (Berita brt : MenuUser.listBerita){
            if(brt.getkodeBerita() == MenuUser.IDBR){
                String [] news = brt.display();
                lbjudul.setText("<HTML>"+news[0]+"</HTML>");
                lbpenulis.setText("<HTML>"+news[1]+"</HTML>");
                lbtgl1.setText("<HTML>"+news[2]+"</HTML>");
                lbisi.setText("<HTML>"+news[3]+"</HTML>");
                
                lbjudul.setHorizontalAlignment(JLabel.CENTER);
                lbtgl.setHorizontalAlignment(JLabel.RIGHT);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnback = new javax.swing.JButton();
        lbisi = new javax.swing.JLabel();
        lbjudul = new javax.swing.JLabel();
        lbpenulis = new javax.swing.JLabel();
        lbtgl1 = new javax.swing.JLabel();
        lbtgl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(575, 695));
        getContentPane().setLayout(null);

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(490, 630, 72, 23);

        lbisi.setBackground(new java.awt.Color(255, 255, 255));
        lbisi.setText("jLabel1");
        getContentPane().add(lbisi);
        lbisi.setBounds(6, 138, 559, 20);

        lbjudul.setBackground(new java.awt.Color(255, 255, 255));
        lbjudul.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbjudul.setText("jLabel1");
        getContentPane().add(lbjudul);
        lbjudul.setBounds(6, 6, 559, 48);

        lbpenulis.setText("jLabel1");
        getContentPane().add(lbpenulis);
        lbpenulis.setBounds(6, 60, 175, 16);

        lbtgl1.setText("jLabel1");
        getContentPane().add(lbtgl1);
        lbtgl1.setBounds(390, 60, 175, 16);

        lbtgl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wahidiyanpost/Desain tanpa judul (1).png"))); // NOI18N
        lbtgl.setText("jLabel1");
        getContentPane().add(lbtgl);
        lbtgl.setBounds(-5, 0, 580, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        MenuUser MU = new MenuUser();
        MU.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JLabel lbisi;
    private javax.swing.JLabel lbjudul;
    private javax.swing.JLabel lbpenulis;
    private javax.swing.JLabel lbtgl;
    private javax.swing.JLabel lbtgl1;
    // End of variables declaration//GEN-END:variables
}
