/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wahidiyanpost;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.Berita;

/**
 *
 * @author Lenovo - GK
 */
public class LihatBerita extends javax.swing.JFrame {

    /**
     * Creates new form LihatBerita
     */
    private Connection con;
    private Statement stat;
    private ResultSet res;

    public static ArrayList<Berita> listBerita = new ArrayList();

    public static int IDB;

    public LihatBerita() {
        initComponents();
        listBerita.clear();
        tabel();
    }

    private void tabel() {
        con = koneksi.getConnection();
        DefaultTableModel tb = (DefaultTableModel) table.getModel();
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tb.setRowCount(0);

        try {
            stat = con.createStatement();
            String sql = "SELECT kode_berita, username, judul, jenis, tgl_berita, isi FROM berita JOIN akun ON berita.id_penulis = akun.id_akun";
            res = stat.executeQuery(sql);
            while (res.next()) {
                Berita brt = new Berita(
                        res.getInt("kode_berita"),
                        res.getString("username"),
                        res.getString("judul"),
                        res.getString("jenis"),
                        res.getString("tgl_berita"),
                        res.getString("isi"));
                listBerita.add(brt);
            }

            for (Berita brt : listBerita) {
                tb.addRow(new Object[]{
                    brt.getkodeBerita(),
                    brt.getPenulis(),
                    brt.getJudul(),
                    brt.getJenis(),
                    brt.getTanggal(),
                    brt.getIsi()
                });
            }

            res.close();
            stat.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }

    private void tabel(String search) {
        con = koneksi.getConnection();
        DefaultTableModel tb = (DefaultTableModel) table.getModel();
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tb.setRowCount(0);

        try {
            stat = con.createStatement();
            String sql = "SELECT kode_berita, username, judul, jenis, tgl_berita, isi FROM berita "
                    + "JOIN akun ON berita.id_penulis = akun.id_akun "
                    + "WHERE username LIKE '%" + search + "%' "
                    + "OR judul LIKE '%" + search + "%' "
                    + "OR jenis LIKE '%" + search + "%' "
                    + "OR isi LIKE '%" + search + "%'";
            res = stat.executeQuery(sql);
            while (res.next()) {
                tb.addRow(new Object[]{
                    res.getInt("kode_berita"),
                    res.getString("username"),
                    res.getString("judul"),
                    res.getString("jenis"),
                    res.getDate("tgl_berita").toString(),
                    res.getString("isi")
                });
            }
            res.close();
            stat.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        btnhapus = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode Berita", "Nama Penulis", "Judul Berita", "Jenis Berita", "Tanggal Berita", "Isi"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 61, 798, 402);

        txtsearch.setBackground(java.awt.SystemColor.control);
        txtsearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtsearch);
        txtsearch.setBounds(580, 30, 200, 20);

        btnhapus.setBackground(new java.awt.Color(255, 255, 204));
        btnhapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnhapus);
        btnhapus.setBounds(418, 32, 72, 23);

        btnubah.setBackground(new java.awt.Color(255, 255, 204));
        btnubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah);
        btnubah.setBounds(334, 32, 72, 23);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.focusColor"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 60);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));

        jMenu2.setBackground(new java.awt.Color(0, 153, 204));
        jMenu2.setForeground(new java.awt.Color(0, 153, 255));
        jMenu2.setText("Home");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        MenuAdmin MA = new MenuAdmin();
        MA.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        String cari = txtsearch.getText();
        tabel(cari);
    }//GEN-LAST:event_txtsearchKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int baris = table.getSelectedRow();
        IDB = (Integer) table.getValueAt(baris, 0);
        System.out.println(IDB);
    }//GEN-LAST:event_tableMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        if (IDB != 0) {
            int response = JOptionPane.showConfirmDialog(this, "Apakah Ingin Menghapus Berita Dengan Kode Berita " + IDB, "Konfirmasi", JOptionPane.YES_NO_OPTION);

            switch (response) {
                case JOptionPane.YES_OPTION:
                    try {
                        Connection conn = koneksi.getConnection();
                        String sql = "DELETE FROM berita WHERE kode_berita = ?";
                        PreparedStatement stmt = conn.prepareStatement(sql);
                        stmt.setInt(1, IDB);

                        int rowAffected = stmt.executeUpdate();
                        if (rowAffected > 0) {
                            for (int i = 0; i < listBerita.size(); i++) {
                                Berita berita = listBerita.get(i);
                                if (berita.getkodeBerita() == IDB) {
                                    listBerita.remove(i);
                                }
                            }
                            IDB = 0;
                            JOptionPane.showMessageDialog(this, "Berhasil Menghapus Berita!", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
                            stmt.close();
                            DefaultTableModel tb = (DefaultTableModel) table.getModel();
                            table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
                            tb.setRowCount(0);
                            for (Berita brt : listBerita) {
                                tb.addRow(new Object[]{
                                    brt.getkodeBerita(),
                                    brt.getPenulis(),
                                    brt.getJudul(),
                                    brt.getJenis(),
                                    brt.getTanggal(),
                                    brt.getIsi()
                                });
                            }
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
                default:
                    throw new AssertionError();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Harap Pilih Data Terlebih Dahulu!");
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        UbahBerita UB = new UbahBerita();
        UB.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnubahActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnubah;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
