/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wahidiyanpost;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo - GK
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        jLabel5.setVisible(false);
        txtkode.setVisible(false);
        
    }

    private void cls() {
        txtusername.setText("");
        txtpassword.setText("");
        txtkpassword.setText("");
        rbyes.setSelected(false);
        rbno.setSelected(false);
        txtkode.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbyes = new javax.swing.JRadioButton();
        rbno = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btnregister = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        txtkpassword = new javax.swing.JPasswordField();
        txtkode = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 330));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(59, 58, 70, 16);
        getContentPane().add(txtusername);
        txtusername.setBounds(187, 55, 173, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(59, 92, 80, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Konfirmasi Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(59, 126, 120, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Penulis ?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(59, 159, 60, 16);

        buttonGroup1.add(rbyes);
        rbyes.setText("Iya");
        rbyes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbyesActionPerformed(evt);
            }
        });
        getContentPane().add(rbyes);
        rbyes.setBounds(187, 157, 50, 21);

        buttonGroup1.add(rbno);
        rbno.setText("Tidak");
        rbno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnoActionPerformed(evt);
            }
        });
        getContentPane().add(rbno);
        rbno.setBounds(262, 157, 98, 21);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Kode Konfirmasi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(59, 193, 100, 16);

        btnback.setBackground(new java.awt.Color(0, 153, 204));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(288, 230, 72, 23);

        btnregister.setBackground(new java.awt.Color(0, 153, 204));
        btnregister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnregister.setText("Register");
        btnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnregister);
        btnregister.setBounds(201, 230, 80, 23);
        getContentPane().add(txtpassword);
        txtpassword.setBounds(187, 89, 173, 22);
        getContentPane().add(txtkpassword);
        txtkpassword.setBounds(187, 123, 173, 22);
        getContentPane().add(txtkode);
        txtkode.setBounds(187, 190, 173, 22);

        jPanel1.setBackground(java.awt.SystemColor.info);

        jLabel6.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("REGISTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel6)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addContainerGap(253, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisterActionPerformed
        // TODO add your handling code here:
        String usn, pw, kpw, penulis = null;

        usn = txtusername.getText();
        pw = new String(txtpassword.getPassword());
        kpw = new String(txtkpassword.getPassword());

        if (rbyes.isSelected() == true) {
            penulis = rbyes.getText();
        } else if (rbno.isSelected() == true) {
            penulis = rbno.getText();
        }

        if (!usn.isEmpty() && !pw.isEmpty() && !kpw.isEmpty() && !penulis.isEmpty()) {

            if (pw.equals(kpw)) {

                if (penulis.equals("Iya")) {

                    String kode = new String(txtkode.getPassword());

                    if (kode.equals("1112")) {

                        try {
                            Connection conn = koneksi.getConnection();
                            String sql = "INSERT INTO akun VALUES (NULL, ?, ?, ?)";
                            PreparedStatement stmt = conn.prepareStatement(sql);
                            stmt.setString(1, usn);
                            stmt.setString(2, pw);
                            stmt.setBoolean(3, true);

                            int rowAffected = stmt.executeUpdate();
                            if (rowAffected > 0) {
                                cls();
                                JOptionPane.showMessageDialog(this, "Berhasil Melakukan Regist!", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
                                Login login = new Login();
                                stmt.close();
                                login.setVisible(true);
                                dispose();
                            }
                        } catch (SQLException e) {
                            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
                        }

                    } else if (!kode.equals("1112")) {
                        JOptionPane.showMessageDialog(this, "Kode Konfimasi Salah", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Harap Isi Kode Konfirmasi!", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else if (penulis.equals("Tidak")) {

                    try {
                        Connection conn = koneksi.getConnection();
                        String sql = "INSERT INTO akun VALUES (NULL, ?, ?, ?)";
                        PreparedStatement stmt = conn.prepareStatement(sql);
                        stmt.setString(1, usn);
                        stmt.setString(2, pw);
                        stmt.setBoolean(3, false);

                        int rowAffected = stmt.executeUpdate();
                        if (rowAffected > 0) {
                            cls();
                            JOptionPane.showMessageDialog(this, "Berhasil Melakukan Regist!", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
                            Login login = new Login();
                            stmt.close();
                            login.setVisible(true);
                            dispose();
                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
                    }

                }

            } else {
                JOptionPane.showMessageDialog(this, "Password dan Konfirmasi Password Tidak Sama!", "Warning", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Harap Inputkan Semua Data!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnregisterActionPerformed

    private void rbyesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbyesActionPerformed
        // TODO add your handling code here:
        jLabel5.setVisible(true);
        txtkode.setVisible(true);
    }//GEN-LAST:event_rbyesActionPerformed

    private void rbnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnoActionPerformed
        // TODO add your handling code here:
        jLabel5.setVisible(false);
        txtkode.setVisible(false);
    }//GEN-LAST:event_rbnoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnregister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbno;
    private javax.swing.JRadioButton rbyes;
    private javax.swing.JPasswordField txtkode;
    private javax.swing.JPasswordField txtkpassword;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
