/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wahidiyanpost;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo - GK
 */
public class UbahBerita extends javax.swing.JFrame {

    /**
     * Creates new form TambahBerita
     */
    private Connection con;
    private Statement stat;
    private ResultSet res;
    
    private void cls() {
        txtjudul.setText("");
        txtisi.setText("");
        Date date = new Date();
        datechoose.setDate(date);
        cbjenis.setSelectedItem("Bencana");
    }

    public UbahBerita() {
        initComponents();
        Date date = new Date();
        datechoose.setMaxSelectableDate(date);
        loadInput();
    }

    private void loadInput() {
        con = koneksi.getConnection();
        try {
            String sql = "SELECT judul,jenis,tgl_berita,isi FROM berita WHERE kode_berita = " + LihatBerita.IDB;
            stat = con.createStatement();
            res = stat.executeQuery(sql);

            if (res.next()) {
                this.txtjudul.setText(res.getString("judul"));
                this.txtisi.setText(res.getString("isi"));
                this.datechoose.setDate(res.getDate("tgl_berita"));
                this.cbjenis.setSelectedItem(res.getString("jenis"));
            }
            res.close();
            stat.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtjudul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbjenis = new javax.swing.JComboBox<>();
        jlabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtisi = new javax.swing.JTextArea();
        btnback = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        datechoose = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));
        setPreferredSize(new java.awt.Dimension(541, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Judul Berita");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(82, 67, 80, 16);

        txtjudul.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtjudul);
        txtjudul.setBounds(233, 64, 234, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Jenis Berita");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(82, 101, 80, 16);

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bencana", "Duka", "Keuangan", "Kriminal", "Sport", "Politik" }));
        getContentPane().add(cbjenis);
        cbjenis.setBounds(233, 98, 234, 22);

        jlabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlabel3.setText("Tanggal Berita");
        getContentPane().add(jlabel3);
        jlabel3.setBounds(82, 132, 90, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Isi Berita");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(82, 160, 60, 16);

        txtisi.setColumns(20);
        txtisi.setRows(5);
        jScrollPane1.setViewportView(txtisi);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(233, 160, 234, 140);

        btnback.setBackground(new java.awt.Color(0, 153, 204));
        btnback.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(395, 318, 72, 23);

        btnubah.setBackground(new java.awt.Color(0, 153, 204));
        btnubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        getContentPane().add(btnubah);
        btnubah.setBounds(311, 318, 72, 23);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(82, 67, 0, 0);

        datechoose.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(datechoose);
        datechoose.setBounds(230, 130, 240, 22);

        jPanel1.setBackground(java.awt.SystemColor.info);

        jLabel5.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("UBAH BERITA");
        jPanel1.add(jLabel5);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        LihatBerita LB = new LihatBerita();
        LB.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        String judul, jenis, tgl, isi;
        judul = txtjudul.getText();
        jenis = cbjenis.getSelectedItem().toString();
        isi = txtisi.getText();
        java.util.Date date = datechoose.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        tgl = sdf.format(date);
        
        con = koneksi.getConnection();
        try {
            String sql = "UPDATE berita SET judul = ?, jenis = ?, tgl_berita = ?, isi = ? WHERE kode_berita = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, judul);
            stmt.setString(2, jenis);
            stmt.setString(3, tgl);
            stmt.setString(4, isi);
            stmt.setInt(5, LihatBerita.IDB);

            int rowAffected = stmt.executeUpdate();
            if (rowAffected > 0) {
                cls();
                JOptionPane.showMessageDialog(this, "Berhasil Mengubah Data Berita!", "SQL Information", JOptionPane.INFORMATION_MESSAGE);
                LihatBerita LB = new LihatBerita();
                stmt.close();
                LB.setVisible(true);
                dispose();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnubahActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnubah;
    private javax.swing.JComboBox<String> cbjenis;
    private com.toedter.calendar.JDateChooser datechoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JTextArea txtisi;
    private javax.swing.JTextField txtjudul;
    // End of variables declaration//GEN-END:variables
}
